services:
  cattlemanagement.api:
    image: ${DOCKER_REGISTRY-}cattlemanagementapi
    build:
      context: .
      dockerfile: src/CattleManagement/CattleManagement.API/Dockerfile
    container_name: cattlemanagement-api-service
    depends_on:
      - cattlemanagement.db
      - kafka
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092

  cattlemanagement.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword123
    volumes:
      - cattlemanagement_data:/var/opt/mssql
    ports:
      - "1433:1433"
    container_name: cattlemanagement-db-service
    restart: unless-stopped

  milkingyield.api:
    image: ${DOCKER_REGISTRY-}milkingyieldapi
    build:
      context: .
      dockerfile: src/MilkingYield/MilkingYield.API/Dockerfile
    container_name: milkingyield-api-service
    depends_on:
      - milkingyield.db
      - kafka
    ports:
      - "5000:5000"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092

  milkingyield.db:
    image: postgres:latest
    container_name: milkingyield-db-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: milkingdb
    volumes:
      - milkingyield_data:/var/lib/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - milkingyield.api
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-service
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-service
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    restart: unless-stopped

volumes:
  cattlemanagement_data:
  milkingyield_data:
  zookeeper_data:
  kafka_data:

